### ISSUE TITLE
Deprecate in favour of ipfs-provider

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/window.ipfs-fallback#3]
## Context

`window.ipfs-fallback` was created as an exploration in opportunistic upgrade of  IPFS experience using API exposed by [ipfs-companion](https://github.com/ipfs/ipfs-companion).

Since then, we created more advanced [ipfs-redux-bundle](https://github.com/ipfs-shipyard/ipfs-redux-bundle) for use in [ipfs-webui](https://github.com/ipfs-shipyard/ipfs-webui/) and @fsdiogo started work on extracting logic into a new, framework-and-backend-agnostic library [ipfs-provider](https://github.com/ipfs-shipyard/ipfs-provider), which supports `window.ipfs` as one of its backends.

This means we now have three libraries, and should start planning convergence around the versatile [ipfs-provider](https://github.com/ipfs-shipyard/ipfs-provider).

## Deprecation Plan

- [x] ensure [ipfs-provider](https://github.com/ipfs-shipyard/ipfs-provider) provides same features as `window.ipfs-fallback` 
     (does not need to be same syntax, but should have more or less feature-parity)
  - [x] `window.ipfs.enable` is supported (https://github.com/ipfs-shipyard/ipfs-provider/issues/1)
- [x] Test and update window.ipfs docs to point at `ipfs-provider`
  - https://github.com/ipfs/ipfs-docs-v2/pull/207
- [x] Update [in-web-browsers/README.md](https://github.com/ipfs/in-web-browsers/blob/master/README.md)
- [x] deprecate `window.ipfs-fallback`
  - [x] update `README`: indicate it is DEPRECATED and replaced with `ipfs-provider`
    ([example of deprecated project](https://github.com/multiformats/go-multicodec))
  - [x] mark deprecated at NPM
- [x] <del>Optional: PR [external projects](https://github.com/ipfs-shipyard/window.ipfs-fallback/network/dependents) that use `window.ipfs-fallback` </del> Marked deprecated at NPM instead, with message pointing at ipfs-provider

## Refs

cc https://github.com/ipfs/in-web-browsers/issues/137 https://github.com/ipfs-shipyard/ipfs-companion/issues/589

**Comment by lidel** [comment]
@alanshaw do you mind releasing a patch release so description on NPM gets updated with deprecation notice and then mark  it as deprecated on NPM?

I feel that should point people at the most flexible library and remove a lot of a lot of confusion.

**Comment by alanshaw** [comment]
You're already a maintainer on npm for this package - any chance you can do the publish?

**Comment by alanshaw** [comment]
Oh, you should also use https://docs.npmjs.com/cli/deprecate

**Comment by lidel** [comment]
Ah.. I've seen only your avatar and made wrong assumption ;-)

Published + added deprecation message.
Will now archive this repo.
